### ISSUE TITLE
appwrite 32bit

### ISSUE THREAD

**Issue by hamidjalili59** [appwrite/docker-mariadb#19]
Hey guys
I wanna use appwrite in linux/arm/v7
What should I do?

**Comment by kodumbeats** [comment]
As far as I know, the only image in the Appwrite stack that doesn't support `armv7` is MariaDB, so the workaround is:

- Clone this repository on the `armv7` system
- Replace the base MariaDB image with a compatible image ([maybe this](https://hub.docker.com/r/linuxserver/mariadb)) in the Dockerfile:
https://github.com/appwrite/docker-mariadb/blob/e07acbf9117012a9010fd5afc44c7a1ee1c43443/Dockerfile#L1
- Build and tag your own image with: `docker build -t yourtag ./Dockerfile`
- Replace the `appwrite/mariadb` with your own in Appwrite's `Docker Compose` file:
https://github.com/appwrite/appwrite/blob/8075ff9692c5542dbd47ed9750f981ff1a3e2f42/docker-compose.yml#L437-L438
- Bring up the Appwrite stack as per the Appwrite docs and proceed as normal.

--------------------------

Gonna close this, as we'll support `armv7` when [upstream](https://hub.docker.com/_/mariadb) brings support.
