### ISSUE TITLE
🐛 Bug Report: Unable to install on my Raspberry pi 3b

### ISSUE THREAD

**Issue by clemorej** [appwrite/docker-mariadb#21]
### 👟 Reproduction steps

This is the error:

```
Pulling mariadb (appwrite/mariadb:1.2.0)...
1.2.0: Pulling from appwrite/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

### 🎲 Docker-MariaDB version

Version 1.2.0

### 💻 Operating system

Linux

**Comment by TorstenDittmann** [comment]
Hey :)

Due to the compatibility of our dependencies like MariaDB, we only support ARMv8 at this point 👍🏻 

You could try [this image](https://github.com/yobasystems/alpine-mariadb), but we will only use official images in our stack.
